name: mnist-train
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.7.5
  - pip
  - pip:
    - azureml-mlflow
    - azureml-sdk
    - scikit-learn==0.24.1
    - pandas==1.2.1
    - joblib==1.0.0
    - matplotlib==3.3.3