variables:

  ap_vm_image: ubuntu-20.04

# Training pipeline settings - Regression

  # Training dataset settings
  training_folder_name: data-science-regression
  training_script_filename: pipeline.yml

# This will change to python-generated yaml in beta 
# Managed Online Endpoint pipeline settings; see sample-deployment.yml in the mlops-templates/src/aml-cli-v2 for reference
  endpoint_name: testEndpoint2  #no spaces or _ allowed; only lowercase, caps, and -