$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline

# <inputs_and_outputs>
inputs:
  pipeline_job_input: #using local data, will crate an anonymous data asset
    type: uri_folder
    path: ./data/

outputs: 
  pipeline_job_transformed_data:
    mode: rw_mount   
  pipeline_job_trained_model:
    mode: rw_mount
  pipeline_job_predictions:
    mode: rw_mount 
  pipeline_job_score_report:
    mode: rw_mount
  pipeline_job_deploy_flag:
    type: uri_folder
# </inputs_and_outputs>

# <jobs>
settings:
  default_datastore: azureml:workspaceblobstore
  default_compute: azureml:cpu-cluster
  continue_on_step_failure: false

jobs:
  prep-job:
    type: command
    component: file:./components/prep/prep.yml
    inputs:
      raw_data: ${{parent.inputs.pipeline_job_input}}
    outputs:
      transformed_data: ${{parent.outputs.pipeline_job_transformed_data}}

  train-job:
    type: command
    component: file:./components/train/train.yml
    inputs:
      training_data: ${{parent.jobs.prep-job.outputs.transformed_data}}
    outputs:
      model_output: ${{parent.outputs.pipeline_job_trained_model}}
  
  evaluate-job:
    type: command
    component: file:./components/evaluate/evaluate.yml
    inputs:
      model_name: "taxi-model"
      model_input: ${{parent.jobs.train-job.outputs.model_output}}
      test_data: ${{parent.jobs.prep-job.outputs.transformed_data}}
    outputs:
      predictions: ${{parent.outputs.pipeline_job_predictions}}
      score_report: ${{parent.outputs.pipeline_job_score_report}}
      deploy_flag: ${{parent.outputs.pipeline_job_deploy_flag}}

  register-job:
    type: command
    component: file:./components/register/register.yml
    inputs:
      model_name: "taxi-model"
      model_path: ${{parent.jobs.train-job.outputs.model_output}}
      deploy_flag: ${{parent.jobs.evaluate-job.outputs.deploy_flag}}

# </jobs>
