# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

variables:
- ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
    # 'main' branch: PRD environment
    - template: ../../../config-infra-prod.yml
- ${{ if ne(variables['Build.SourceBranchName'], 'main') }}:  
    # 'develop' or feature branches: DEV environment
    - template: ../../../config-infra-dev.yml
- name: version
  value: aml-cli-v2 #must be either 'python-sdk' or 'aml-cli-v2'
- name: endpoint_name
  value: batchendpoint1
- name: endpoint_type
  value: batch

trigger:
- none

pool:
  vmImage: ubuntu-20.04


resources:
  repositories:
    - repository: mlops-templates  # Template Repo
      name: Azure/mlops-templates # need to change org name from "Azure" to your own org
      endpoint: mlops-v2-service-connection  # need to hardcode as repositories doesn't accept variables
      type: github

stages:
- stage: DeployTrainingPipeline
  displayName: Deploy Training Pipeline
  jobs:
    - job: DeployTrainingPipeline
      steps:
      - checkout: self
        path: s/
      - checkout: mlops-templates
        path: s/templates/
      - template: templates/${{ variables.version }}/install-az-cli.yml@mlops-templates
      - template: templates/${{ variables.version }}/install-aml-cli.yml@mlops-templates
      - template: templates/${{ variables.version }}/connect-to-workspace.yml@mlops-templates
      - template: templates/${{ variables.version }}/run-pipeline.yml@mlops-templates
        parameters: 
          pipeline_file: data-science-regression/pipeline.yml
      condition: eq(variables['build.sourceBranchName'], 'main') # Selective skipping based on branch; remove this line before release!


- stage: CreateBatchEndpoint
  displayName: Create/Update Batch Endpoint 
  jobs:
    - job: DeployBatchEndpoint
      steps:
      - checkout: self
        path: s/
      - checkout: mlops-templates
        path: s/templates/
      - template: templates/${{ variables.version }}/install-az-cli.yml@mlops-templates
      - template: templates/${{ variables.version }}/install-aml-cli.yml@mlops-templates
      - template: templates/${{ variables.version }}/connect-to-workspace.yml@mlops-templates
      - template: templates/${{ variables.version }}/create-compute.yml@mlops-templates
        parameters:
          cluster_name: batch-cluster # name must match cluster name in deployment file below
          min_instances: 0
          max_instances: 5
      - template: templates/${{ variables.version }}/create-endpoint.yml@mlops-templates
      - template: templates/${{ variables.version }}/create-deployment.yml@mlops-templates
        parameters:
          deployment_name: mlflowdp
          deployment_file: data-science-regression/components/deploy/batch-endpoint/mlflow-deployment.yml      
      - template: templates/${{ variables.version }}/test-deployment.yml@mlops-templates
        parameters:
          deployment_name: mlflowdp
          sample_request: file:https://pipelinedata.blob.core.windows.net/sampledata/nytaxi/taxi-tip-data.csv


