blank_issues_enabled: false
  - name: Azure ML CLI issues.
    url: https://github.com/azure/azure-cli-extensions/issues/new/choose
    about: Please open issues with the Azure ML CLI extension here.
  - name: Azure ML Python SDK issues.
    url: https://github.com/azure/azure-sdk-for-python/issues/new/choose
    about: Please open issues with the Azure ML Python SDK here.