trigger: none

name: Initialize ${{ parameters.repoName }} repo

parameters:
  - name: adoProjectName
    displayName: Azure DevOps Project Name
    type: string

  - name: repoName
    displayName: New Project Repository Name
    type: string

  #- name: mlOpsProjectTemplateAdoProjectName
  #  displayName: MLOps Project Template's ADO project name
  #  type: string
  #  # default: [good idea to put your default here]

  - name: mlopsRepoName
    displayName: MLOps-V2 ADO Repository name
    type: string
    default: mlops-v2

  - name: mlOpsProjectRepoName
    displayName: MLOps Project Template's repo
    type: string
    default: mlops-project-template

  - name: projectType
    displayName: ML Project Type
    type: string
    default: classical
    values:
      - classical
      - cv
      - nlp

  - name: mlopsVersion
    displayName: MLOps Interface
    type: string
    default: aml-cli-v2
    values:
      - aml-cli-v2
      - python-sdk-v1
      - python-sdk-v2
      - rai-aml-cli-v2

  - name: infrastructure_version
    displayName: Infrastructure Provider
    type: string
    default: bicep
    values:
      - bicep
      - terraform

stages:
  - stage: InitialiseProject
    displayName: Initialise Project
    jobs:
      - job: InitialiseProjectJob
        displayName: Checkout repos, initialise your new one and create pipelines
        steps:
          - checkout: self
            persistCredentials: false
          #- checkout: git://${{ parameters.mlOpsProjectTemplateAdoProjectName }}/${{ parameters.mlOpsProjectRepoName }}
          #  persistCredentials: false
          - checkout: git://${{ parameters.adoProjectName }}/${{ parameters.mlOpsProjectRepoName }}
            persistCredentials: false
          - checkout: git://${{ parameters.adoProjectName }}/${{ parameters.repoName }}
            persistCredentials: true

          - task: Bash@3
            displayName: Run script to initialise your repo
            inputs:
              targetType: "filePath"
              filePath: ${{ parameters.mlopsRepoName }}/.azuredevops/scripts/initialise_repo.sh
              arguments: >
                ${{ parameters.repoName }} ${{ parameters.projectType }} ${{ parameters.mlopsVersion }} ${{ parameters.mlOpsProjectRepoName }} ${{ parameters.infrastructure_version}}


          - task: Bash@3
            displayName: Run script to create pipelines in ADO
            inputs:
              targetType: "filePath"
              filePath: ${{ parameters.mlopsRepoName }}/.azuredevops/scripts/create_ado_pipelines.sh
              arguments: >
                ${{ parameters.repoName }} ${{ parameters.adoProjectName }}

            env:
              AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
