# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

variables:
- template: ../../../config-aml.yml
- ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
    # 'main' branch: PRD environment
    - template: ../../../config-infra-prod.yml
- ${{ if ne(variables['Build.SourceBranchName'], 'main') }}:  
    # 'develop' or feature branches: DEV environment
    - template: ../../../config-infra-dev.yml

trigger:
- none

pool:
  vmImage: $(ap_vm_image)

resources:
  repositories:
    - repository: mlops-templates 
      name: Azure/mlops-templates 
      endpoint: github.com_murggu 
      type: github

stages :
  - stage: CreateStorageAccountForTerraformState
    displayName: Create Storage for Terraform
    jobs:
    - job: CreateStorageForTerraform
      displayName: Create Storage for Terraform
      steps:
      - checkout: mlops-templates
      - template: templates/infra/create-resource-group
      - template: templates/infra/create-storage-account
      - template: templates/infra/create-container
  - stage: DeployAzureMachineLearningRG
    displayName: Deploy AML Resource Group
    jobs:
    - job:  DeployAMLWorkspace
      displayName: 'Deploy AML Workspace'
      steps:
      - checkout: mlops-templates
      - template: templates/infra/install-terraform
      - template: templates/infra/run-terraform-init
      - template: templates/infra/run-terraform-validate
      - template: templates/infra/run-terraform-plan
      - template: templates/infra/run-terraform-apply