variables:
- template: ../controller-config.yml

trigger:
- none

pool:
  vmImage: ubuntu-20.04

resources:
  repositories:
    - repository: templates-mlops  # Template Repo
      name: ai-factory-azure/templates-mlops
      endpoint: Github-Service-Endpoint
      type: github

stages:
- stage: DeployTrainingPipeline
  displayName: Deploy Training Pipeline
  jobs:
    - job: DeployTrainingPipeline
      steps:
      - checkout: self
        path: s/
      - checkout: templates-mlops
        path: s/templates/
      - template: templates/install-az-cli.yml@templates-mlops
      - template: templates/install-aml-cli.yml@templates-mlops
      - template: templates/connect-to-workspace.yml@templates-mlops
      - template: templates/create-environment.yml@templates-mlops
        parameters:
          environment_name: $(training_environment_name)
          environment_conda_yaml: $(training_environment_conda_yaml)
      - template: templates/register-dataset.yml@templates-mlops
        parameters:
          data_type: training
      - template: templates/get-compute.yml@templates-mlops
        parameters:
          compute_type: training
      - template: templates/deploy-training-pipeline.yml@templates-mlops
      - template: templates/add-pipeline-to-endpoint.yml@templates-mlops
      - template: templates/run-pipeline.yml@templates-mlops