variables:
- template: ../../config.yml

trigger:
- none

pool:
  vmImage: ubuntu-20.04

resources:
  repositories:
    - repository: mlops-templates  # Template Repo
      name: Azure/mlops-templates
      endpoint: Github-Service-Endpoint
      type: github

stages:
- stage: DeployTrainingPipeline
  displayName: Deploy Training Pipeline
  jobs:
    - job: DeployTrainingPipeline
      steps:
      - checkout: self
        path: s/
      - checkout: mlops-templates
        path: s/templates/
      - template: templates/install-az-cli.yml@mlops-templates
      - template: templates/install-aml-cli.yml@mlops-templates
      - template: templates/connect-to-workspace.yml@mlops-templates
      - template: templates/create-environment.yml@mlops-templates
        parameters:
          environment_name: $(training_environment_name)
          environment_conda_yaml: $(training_environment_conda_yaml)
      - template: templates/register-dataset.yml@mlops-templates
        parameters:
          data_type: training
      - template: templates/get-compute.yml@mlops-templates
        parameters:
          compute_type: training
      - template: templates/deploy-training-pipeline.yml@mlops-templates
      - template: templates/add-pipeline-to-endpoint.yml@mlops-templates
      - template: templates/run-pipeline.yml@mlops-templates