variables:
- template: ../../config-aml.yml
- name: version
  value: python-sdk

trigger:
- none

pool:
  vmImage: ubuntu-20.04

resources:
  repositories:
    - repository: mlops-templates  # Template Repo
      name: Azure/mlops-templates
      endpoint: mlops-v2-tabular
      type: github

stages:
- stage: DeployTrainingPipeline
  displayName: Deploy Training Pipeline
  jobs:
    - job: DeployTrainingPipeline
      steps:
      - checkout: self
        path: s/
      - checkout: mlops-templates
        path: s/templates/
      - template: templates/$(version)/install-az-cli.yml@mlops-templates
      - template: templates/$(version)/install-aml-cli.yml@mlops-templates
      - template: templates/$(version)/connect-to-workspace.yml@mlops-templates
      - template: templates/$(version)/create-environment.yml@mlops-templates
        parameters:
          environment_name: $(training_environment_name)
          environment_conda_yaml: $(training_environment_conda_yaml)
      - template: templates/$(version)/register-dataset.yml@mlops-templates
        parameters:
          data_type: training
      - template: templates/$(version)/get-compute.yml@mlops-templates
        parameters:
          compute_type: training
      - template: templates/$(version)/deploy-training-pipeline.yml@mlops-templates
      - template: templates/$(version)/add-pipeline-to-endpoint.yml@mlops-templates
      - template: templates/$(version)/run-pipeline.yml@mlops-templates