variables:
- template: ../controller-config.yml

trigger:
- main

pool:
  vmImage: ubuntu-20.04

resources:
  repositories:
    - repository: mlops-templates  # Template Repo
      name: Azure/mlops-templates # need to change org name from Azure when pulling the template
      endpoint: mlops-v2-tabular # need to hardcode!
      type: github

stages:
- stage: DeployTrainingPipeline
  displayName: Deploy Training Pipeline
  jobs:
    - job: DeployManagedOnlineEndpoint
      steps:
      - checkout: self
        path: s/
      - checkout: mlops-templates
        path: s/templates/
      - template: templates/aml-cli-v2/install-aml-cli-v2.yml@mlops-templates
      - template: templates/aml-cli-v2/connect-to-workspace-v2.yml@mlops-templates
      - template: templates/aml-cli-v2/deploy-managed-online-endpoint.yml@mlops-templates
        parameters:
          job_type: create-deployment
      - template: templates/aml-cli-v2/deploy-managed-online-endpoint.yml@mlops-templates
        parameters:
          job_type: traffic_allocation