# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

variables:
- ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
    # 'main' branch: PRD environment
    - template: ../../config-infra-prod.yml
- ${{ if ne(variables['Build.SourceBranchName'], 'main') }}:  
    # 'develop' or feature branches: DEV environment
    - template: ../../config-infra-dev.yml
- name: version
  value: aml-cli-v2 #must be either 'python-sdk' or 'aml-cli-v2'
- name: endpoint_name
  value: demoEndpoint1

trigger:
- none

pool:
  vmImage: ubuntu-20.04


resources:
  repositories:
    - repository: mlops-templates  # Template Repo
      name: Azure/mlops-templates # need to change org name from "Azure" to your own org
      endpoint: mlops-v2-service-connection  # need to hardcode as repositories doesn't accept variables
      type: github

stages:
- stage: DeployTrainingPipeline
  displayName: Deploy Training Pipeline
  jobs:
    - job: DeployTrainingPipeline
      steps:
      - checkout: self
        path: s/
      - checkout: mlops-templates
        path: s/templates/
      - template: templates/${{ variables.version }}/install-az-cli.yml@mlops-templates
      - template: templates/${{ variables.version }}/install-aml-cli.yml@mlops-templates
      - template: templates/${{ variables.version }}/connect-to-workspace.yml@mlops-templates
      - template: templates/${{ variables.version }}/run-pipeline.yml@mlops-templates
        parameters: 
          pipeline_file: data-science-regression/pipeline.yml

- stage: CreateOnlineEndpoint
  displayName: Create Online Endpoint
  jobs:
    - job: DeployOnlineEndpoint
      steps:
      - checkout: self
        path: s/
      - checkout: mlops-templates
        path: s/templates/
      - template: templates/${{ variables.version }}/install-az-cli.yml@mlops-templates
      - template: templates/${{ variables.version }}/install-aml-cli.yml@mlops-templates
      - template: templates/${{ variables.version }}/connect-to-workspace.yml@mlops-templates
      - template: templates/${{ variables.version }}/create-endpoint.yml@mlops-templates
      - template: templates/${{ variables.version }}/create-deployment.yml@mlops-templates
        parameters:
          deployment_name: blue
          deployment_file: data-science-regression/components/deploy/blue/blue-deployment.yml 
      - template: templates/${{ variables.version }}/allocate-traffic.yml@mlops-templates
        parameters:
          traffic_allocation: blue=100
      - template: templates/${{ variables.version }}/test-deployment.yml@mlops-templates

# Example: Update existing deployment; as you'd probably never update an endpoint immediately after creating it
- stage: UpdateOnlineEndpoint
  displayName: Update Online Endpoint
  jobs:
    - job: DeployOnlineEndpoint
      steps:
      - checkout: self
        path: s/
      - checkout: mlops-templates
        path: s/templates/
      - template: templates/${{ variables.version }}/install-az-cli.yml@mlops-templates
      - template: templates/${{ variables.version }}/install-aml-cli.yml@mlops-templates
      - template: templates/${{ variables.version }}/connect-to-workspace.yml@mlops-templates
      - template: templates/${{ variables.version }}/update-deployment.yml@mlops-templates
        parameters:
          deployment_name: blue
          deployment_file: data-science-regression/components/deploy/blue/blue-deployment.yml 
      - template: templates/${{ variables.version }}/test-deployment.yml@mlops-templates


# Example: Safe Rollout, can also be used for A/B testing 
- stage: SafeRollout
  displayName: Safe rollout of new deployment
  jobs:
    - job: DeployOnlineEndpoint
      steps:
      - checkout: self
        path: s/
      - checkout: mlops-templates
        path: s/templates/
      - template: templates/${{ variables.version }}/install-az-cli.yml@mlops-templates
      - template: templates/${{ variables.version }}/install-aml-cli.yml@mlops-templates
      - template: templates/${{ variables.version }}/connect-to-workspace.yml@mlops-templates
      - template: templates/${{ variables.version }}/create-deployment.yml@mlops-templates
        parameters:
          deployment_name: green
          deployment_file: data-science-regression/components/deploy/green/green-deployment.yml 
      - template: templates/${{ variables.version }}/allocate-traffic.yml@mlops-templates
        parameters:
          traffic_allocation: blue=90 green=10
      - template: templates/${{ variables.version }}/test-deployment.yml@mlops-templates
